version: '3'

services:
  app:
    build: docker
    ports:
        - '9000:9000'
    volumes:
        - ./app:/home/nodejs/app
    tty: true

  redis:
    image: redis:latest
    ports:
        - '6379:6379'
volumes:
  app:
    driver: local