version: 2
jobs:
  build:
    working_directory: ~/slack-clean
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/slack-clean/app/package.json"}}
            - v1-dependencies-

      - run:
          name: install-npm
          command: cd ~/slack-clean/app && npm install

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ~/slack-clean/app/cc-test-reporter
            chmod +x ~/slack-clean/app/cc-test-reporter

      - save_cache:
          key: v1-dependencies-{{ checksum "~/slack-clean/app/package.json"}}
          paths:
            - ~/slack-clean/app/node_modules

      - run:
          name: test-coverage
          command: |
            cd ~/slack-clean/app
            ./cc-test-reporter before-build
            npm run test-coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
            ./cc-test-reporter after-build --exit-code $?
